apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: multi-app-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-listener-app-1
      interceptors:
      - ref:
          name: "github"
          kind: ClusterInterceptor
          apiVersion: triggers.tekton.dev
        params:
        - name: "addChangedFiles"
          value:
            enabled: true
      - ref:
          name: cel
        params:
        - name: "filter"
          value: 'header.match("X-GitHub-Event", "push") && extensions.changed_files.matches("app-1/src/")'
        - name: "overlays"
          value:
          - key: branch
            expression: "body.ref.split('/')[2]"
      bindings:
        - ref: app-pipeline-binding
      template:
        ref: app-1-pipeline-template
    - name: github-listener-app-2
      interceptors:
      - ref:
          name: "github"
          kind: ClusterInterceptor
          apiVersion: triggers.tekton.dev
        params:
        - name: "addChangedFiles"
          value:
            enabled: true
      - ref:
          name: cel
        params:
        - name: "filter"
          value: 'header.match("X-GitHub-Event", "push") && extensions.changed_files.matches("app-2/src/")'
        - name: "overlays"
          value:
          - key: branch
            expression: "body.ref.split('/')[2]"
      bindings:
        - ref: app-pipeline-binding
      template:
        ref: app-2-pipeline-template
