apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: simple-pipeline-listener-interceptor
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-listener-app-1
      interceptors:
      - ref:
          name: "github"
          kind: ClusterInterceptor
          apiVersion: triggers.tekton.dev
        params:
        - name: "addChangedFiles"
          value:
            enabled: true
      - ref:
          name: cel
        params:
        - name: "filter"
          value: 'body["ref"].contains("main") && body["repository"]["name"] == "simple-apps" && header.match("X-GitHub-Event", "push") && extensions.changed_files.matches("controllers/")'
        - name: "overlays"
          value:
          - key: branch
            expression: "body.ref.split('/')[2]"
#      interceptors:
#        - webhook:
#            objectRef:
#              kind: Service
#              name: trigger-filter
#              apiVersion: v1
      bindings:
        - ref: app-1-pipeline-binding
      template:
        ref: app-1-pipeline-template
    - name: github-listener-app-2
      interceptors:
      - ref:
          name: cel
        params:
        - name: "filter"
          value: 'body["ref"].contains("main-xxx") && body["repository"]["name"] == "simple-apps" && header.match("X-GitHub-Event", "push")'
        - name: "overlays"
          value:
          - key: branch
            expression: "body.ref.split('/')[2]"
        - name: "addChangedFiles"
          value:
            enabled: true
            personalAccessToken:
              secretName: github-access-token
              secretKey: token
#      interceptors:
#        - webhook:
#            objectRef:
#              kind: Service
#              name: trigger-filter
#              apiVersion: v1
      bindings:
        - ref: app-2-pipeline-binding
      template:
        ref: app-2-pipeline-template
