apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
#- app-project.yaml
- deployment.yaml

patches: 
  - patch: |-
      - op: replace
        path: /metadata/name
        value: argo-app-5
    target:
      labelSelector: kustomizeIdentifer=app-to-update
  - patch: |-
      - op: replace
        path: /metadata/labels/app
        value: argo-app-5
    target:
      labelSelector: kustomizeIdentifer=app-to-update
  - patch: |-
      - op: replace
        path: /spec/selector/matchLabels/deployment
        value: argo-app-5
    target:
      labelSelector: kustomizeIdentifer=app-to-update
      kind: Deployment
  - patch: |-
      - op: replace
        path: /spec/selector/matchLabels/app
        value: argo-app-5
    target:
      labelSelector: kustomizeIdentifer=app-to-update
      kind: Deployment
  - patch: |-
      - op: replace
        path: /spec/template/metadata/labels/deployment
        value: argo-app-5
    target:
      labelSelector: kustomizeIdentifer=app-to-update
      kind: Deployment
  - patch: |-
      - op: replace
        path: /spec/template/metadata/labels/app
        value: argo-app-5
    target:
      labelSelector: kustomizeIdentifer=app-to-update
      kind: Deployment
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: argo-app-5
    target:
      labelSelector: kustomizeIdentifer=app-to-update
      kind: Deployment
  - patch: |-
      - op: replace
        path: /spec/selector/app
        value: argo-app-5
    target:
      labelSelector: kustomizeIdentifer=app-to-update
      kind: Service
  - patch: |-
      - op: replace
        path: /spec/to/name
        value: argo-app-5
    target:
      labelSelector: kustomizeIdentifer=app-to-update
      kind: Route
      
      