apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: skopeo-inspect
spec:
  params:
    - name: image-url
      type: string
  steps:
    - name: gen-binary-extraction-dockerfile
      command:
        - /bin/sh
        - '-c'
      args:
        - |-
          skopeo inspect docker://$(params.image-url)
      image: registry.redhat.io/rhel8/skopeo@sha256:16a9e6d89dbc80cf88fece341e63b99239082aabf705cc014c6350a14fb29509
