apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- route.yaml
- triggers/eventListener.yaml
- triggers/eventListenerRoute.yaml
- triggers/triggerBinding.yaml
- triggers/triggerTemplate.yaml