apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: app-1-pipeline-template
spec:
  params:
  - name: gitrepository.url
  - name: gitrevision
  - name: ext-branch
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: pipeline-app-1-pr-tr-
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: pipeline-app-1
      params:
        - name: git-url
          value: $(tt.params.gitrepository.url)
        - name: git-revision
          value: $(tt.params.gitrevision)
        - name: git-branch
          value: $(tt.params.ext-branch)
          # Directory within the git repo that holds the dockerfile. The example dockerfile makes reference to 
          # files within this directory too.
        - name: app-dir
          value: node/multi-apps/app-1/src
          # The imagestream url for where the created container image will be stored. Update the namespace element if this is
          # created in a different namespace. also update the namespace file in the location namespace/namespace.yaml.
        - name: imagestream-url
          value: image-registry.openshift-image-registry.svc:5000/simple-pipeline/app-1
          # If using the push-to-quay task update the following fields.
          # The quay.io user account field.
      workspaces:
      - name: files
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
      - name: resources
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
