kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-2
  labels:
    app: app-2
spec:
  replicas: 10
  selector:
    matchLabels:
      deployment: app-2
      app: app-2
  template:
    metadata:
      labels:
        deployment: app-2
        app: app-2
    spec:
      containers:
        - name: app-2
          image: quay.io/marrober/layers:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 100Mi
---
kind: Service
apiVersion: v1
metadata:
  name: app-2
  labels:
    app: app-2
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: app-2
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: app-2
  name: app-2
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: app-2
    weight: 100