kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-3
  labels:
    app: app-3
spec:
  replicas: 4
  selector:
    matchLabels:
      deployment: app-3
      app: app-3
  template:
    metadata:
      labels:
        deployment: app-3
        app: app-3
    spec:
      containers:
        - name: app-3
          image: quay.io/marrober/layers:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1
              memory: 500Mi
            requests:
              cpu: 50m
              memory: 10Mi
---
kind: Service
apiVersion: v1
metadata:
  name: app-3
  labels:
    app: app-3
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: app-3
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: app-3
  name: app-3
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: app-3
    weight: 100