apiVersion: apps/v1
kind: Deployment
metadata:
  name: smee-pipeline
  labels:
    app.kubernetes.io/part-of: smee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gosmee
  template:
    metadata:
      labels:
        app: gosmee
    spec:
      containers:
        - image: quay.io/marrober/gosmee:latest
          imagePullPolicy: IfNotPresent
          name: gosmee
          args:
            [
              "client",
              "--saveDir",
              "/tmp/save",
              "https://smee.io/p7xxQSdMuMgZfLoN",
              "http://simple-pipeline-listener-el-simple-pipeline.apps.conroe.demolab.local"
            ]
