apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-1
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: ocm-placement-generator
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: app1-app-placement
  template:
    metadata:
      annotations:
        apps.open-cluster-management.io/ocm-managed-cluster: '{{name}}'
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: openshift-gitops
        argocd.argoproj.io/skip-reconcile: "true" 
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true" 
      name: '{{name}}-app-1'
    spec:
      destination:
        namespace: argo-app-1
        server: '{{server}}'
      project: app-1
      source:
        path: Argo-Apps/app-1
        repoURL: https://github.com/marrober/simple-apps.git
        targetRevision: main
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true