apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: app1-app-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - dev-clusters
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            vendor: OpenShift