apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  params:
    - name: STORAGE_DRIVER
      type: string
      default: vfs
    - name: git_url
      type: string
    - name: git_revision
      type: string
    - name: app-dir
      type: string
    - name: TLSVERIFY
      type: string
      default: 'false'
    - name: imagestream-url
      type: string
#   Quay.io configuration
    - name: quay-io-account
      type: string
    - name: quay-io-repository
      type: string
    - name: quay-io-image-tag-name
      type: string
  tasks:
##------------------------------------------------------------------
# Git clone resources task
##------------------------------------------------------------------
    - name: git-clone-resources
      params:
      - name: url
        value: $(params.git_url)
      - name: revision
        value: $(params.git_revision)
      - name: verbose
        value: 'false'
      - name: deleteExisting
        value: 'true'
      taskRef:
        kind: ClusterTask
        name:  git-clone
      workspaces:
      - name: output
        workspace: resources
##------------------------------------------------------------------
# Build the jar file deliverable
##------------------------------------------------------------------
    - name: build
      params:
        - name: STORAGE_DRIVER
          value: $(params.STORAGE_DRIVER)
        - name: app-dir
          value: $(params.app-dir)
      taskRef:
        kind: Task
        name: build
      runAfter:
      - git-clone-resources
      workspaces:
      - name: files
        workspace: files
      - name: resources
        workspace: resources
#------------------------------------------------------------------
# Push the new runtime image to OpenShift imagestream
#------------------------------------------------------------------
    - name: push-image-to-imagestream
      params:
      - name: imagestream-url
        value: $(params.imagestream-url)    
      - name: STORAGE_DRIVER
        value: $(params.STORAGE_DRIVER)
      - name: TLSVERIFY 
        value: "$(params.TLSVERIFY)"
      - name: pipelineRunName
        value: $(context.pipelineRun.name)
      taskRef:
        kind: Task
        name: push-image-to-ocp
      runAfter:
        - build
      workspaces:
      - name: files
        workspace: files
#------------------------------------------------------------------
# Push the new runtime image to Quay.io
#------------------------------------------------------------------
    - name: push-image-to-quay
      params:
      - name: quay-io-account
        value: $(params.quay-io-account)
      - name: quay-io-repository
        value: $(params.quay-io-repository)
      - name: quay-io-image-tag-name
        value: $(tasks.push-image-to-imagestream.results.new-tag)
      - name: STORAGE_DRIVER
        value: $(params.STORAGE_DRIVER)
      taskRef:
        kind: Task
        name: push-image-to-quay
      runAfter:
        - push-image-to-imagestream
      workspaces:
      - name: files
        workspace: files
##------------------------------------------------------------------
# Workspace definitions
##------------------------------------------------------------------
  workspaces:
    - name: resources
    - name: files
