apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  params:
  - name: STORAGE_DRIVER
    type: string
    default: vfs
  - name: git-url
    type: string
  - name: git-revision
    type: string
  - name: gitrepository_fullname
    type: string
  - name: commit_prior_revision
    type: string
  - name: commit_ref
    type: string
  - name: commit_id
    type: string
  - name: commit_date
    type: string
  - name: commit_message
    type: string
  - name: commit_author
    type: string
  - name: quay-io-account
    type: string
    default: "marrober"
  - name: quay-io-repository
    type: string
    default: "simple-pipeline"
  - name: quay-io-image-tag-name
    type: string
    default: "latest"
  - name: app-dir
    type: string
  tasks:
##------------------------------------------------------------------
# Git clone resources task
##------------------------------------------------------------------
  - name: git-clone-resources
    params:
    - name: url
      value: $(params.git-url)
    - name: revision
      value: $(params.git-revision)
    - name: verbose
      value: 'false'
    - name: subdirectory
      value: resources
    taskRef:
      kind: ClusterTask
      name:  git-clone
    workspaces:
    - name: output
      workspace: resources
##------------------------------------------------------------------
# Build the jar file deliverable
##------------------------------------------------------------------
  - name: build
    params:
      - name: STORAGE_DRIVER
        value: $(params.STORAGE_DRIVER)
      - name: gitrepository_url
        value: $(params.url)
      - name: gitrepository_fullname
        value: $(params.gitrepository_fullname)
      - name: commit_prior_revision
        value: $(params.commit_prior_revision)
      - name: commit_ref
        value: $(params.commit_ref)
      - name: commit_id
        value: $(params.commit_id)
      - name: commit_date
        value: $(params.commit_date)
      - name: commit_message
        value: $(params.commit_message)
      - name: commit_author
        value: $(params.commit_author)
      - name: pipelineRunName
        value: $(context.pipelineRun.name)
      - name: pipelineName
        value: $(context.pipeline.name)

    taskRef:
      kind: Task
      name: build
    runAfter:
    - git-clone-resources
    workspaces:
    - name: files
      workspace: files
#------------------------------------------------------------------
# Push the new runtime image to quay.io
#------------------------------------------------------------------
#  - name: push-image-to-quay
#    params:
#      - name: quay-io-account
#        value: $(params.quay-io-account)
#      - name: quay-io-repository
#        value: $(params.quay-io-repository)
#      - name: quay-io-image-tag-name
#        value: $(params.quay-io-image-tag-name)
#      - name: STORAGE_DRIVER
#        value: $(params.STORAGE_DRIVER)
#    taskRef:
#      kind: Task
#      name: push-image-to-quay
#    runAfter:
#      - build
#    workspaces:
#    - name: files
#      workspace: files
##------------------------------------------------------------------
# Workspace definitions
##------------------------------------------------------------------
  workspaces:
  - name: resources
  - name: files
