apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  params:
  - name: STORAGE_DRIVER
    type: string
    default: vfs
  - name: git_url
    type: string
  - name: git_revision
    type: string
  - name: git_fullname
    type: string
  - name: commit_prior_revision
    type: string
  - name: commit_ref
    type: string
  - name: commit_id
    type: string
  - name: commit_date
    type: string
  - name: commit_message
    type: string
  - name: commit_author
    type: string
  - name: quay-io-account
    type: string
    default: "marrober"
  - name: quay-io-repository
    type: string
    default: "simple-pipeline"
  - name: quay-io-image-tag-name
    type: string
    default: "latest"
  - name: app-dir
    type: string
  - name: TLSVERIFY
    type: string
    default: 'false'
  - name: imagestream-url
    type: string
  tasks:
##------------------------------------------------------------------
# Git clone resources task
##------------------------------------------------------------------
  - name: git-clone-resources
    params:
    - name: url
      value: $(params.git_url)
    - name: revision
      value: $(params.git_revision)
    - name: verbose
      value: 'true'
    - name: deleteExisting
      value: 'true'
    taskRef:
      kind: ClusterTask
      name:  git-clone
    workspaces:
    - name: output
      workspace: resources
##------------------------------------------------------------------
# Build the jar file deliverable
##------------------------------------------------------------------
  - name: build
    params:
      - name: STORAGE_DRIVER
        value: $(params.STORAGE_DRIVER)
      - name: git_url
        value: $(params.git_url)
      - name: git_fullname
        value: $(params.git_fullname)
      - name: commit_prior_revision
        value: $(params.commit_prior_revision)
      - name: commit_ref
        value: $(params.commit_ref)
      - name: commit_id
        value: $(params.commit_id)
      - name: commit_date
        value: $(params.commit_date)
      - name: commit_message
        value: $(params.commit_message)
      - name: commit_author
        value: $(params.commit_author)
      - name: pipelineName
        value: $(context.pipeline.name)
      - name: app-dir
        value: $(params.app-dir)
    taskRef:
      kind: Task
      name: build
    runAfter:
    - git-clone-resources
    workspaces:
    - name: files
      workspace: files
    - name: resources
      workspace: resources
#------------------------------------------------------------------
# Push the new runtime image to OpenShift imagestream
#------------------------------------------------------------------
  - name: push-image-to-imagestream
    params:
    - name: imagestream-url
      value: $(params.imagestream-url)    
    - name: STORAGE_DRIVER
      value: $(params.STORAGE_DRIVER)
    - name: TLSVERIFY 
      value: "$(params.TLSVERIFY)"
    - name: pipelineRunName
      value: $(context.pipelineRun.name)
    taskRef:
      kind: Task
      name: push-image-to-ocp
    runAfter:
      - build
    workspaces:
    - name: files
      workspace: files
##------------------------------------------------------------------
# Workspace definitions
##------------------------------------------------------------------
  workspaces:
  - name: resources
  - name: files
