kind: Deployment
apiVersion: apps/v1
metadata:
  name: layers
  labels:
    app: layers
spec:
  replicas: 4
  selector:
    matchLabels:
      deployment: layers
      app: layers
  template:
    metadata:
      labels:
        deployment: layers
        app: layers
    spec:
      containers:
        - name: layers
          image: quay.io/marrober/layers:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 100Mi
---
kind: Service
apiVersion: v1
metadata:
  name: layers
  labels:
    app: layers
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: layers
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: layers
  name: layers
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: layers
    weight: 100