apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- role-bindings/argocd-admin.yaml
- role-bindings/ci-pipeline-role.yaml
- argocd-management-app.yaml
- argocd-project-simple-apps.yaml
- argocd-ci-process.yaml
# - argocd-application.yaml


