apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-2
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: dev-clusters
  template:
    metadata:
      annotations:
        apps.open-cluster-management.io/ocm-managed-cluster: '{{name}}'
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: openshift-gitops
        argocd.argoproj.io/skip-reconcile: "true" 
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true" 
      name: '{{name}}-app-2'
    spec:
      destination:
        namespace: app-2
        server: https://kubernetes.default.svc
      project: app-2
      source:
        path: Argo-Apps/app-2
        repoURL: https://github.com/marrober/simple-apps.git
        targetRevision: main
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true