apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: app-2-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - dev-clusters
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: vendor
          operator: "In"
          values:
          - OpenShift
        - key: environment
          operator: "In"
          values:
          - dev