apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener: simple-pipeline-listener-interceptor
  name: simple-pipeline-listener-el
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-simple-pipeline-listener-interceptor
