apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: simple-pipeline-listener-interceptor
spec:
  serviceAccountName: pipeline
  triggers:
  - name: github-listener
    interceptors:
    - ref:
        name: "github"
        kind: ClusterInterceptor
        apiVersion: triggers.tekton.dev
      params:
      - name: "addChangedFiles"
        value:
          enabled: true    
    - ref:
        name: cel
      params:
      - name: "filter"
        value: 'body["ref"].contains("main") && body["repository"]["name"] == "simple-apps" && header.match("X-GitHub-Event", "push")  && extensions.changed_files.matches("node/layers")'
      - name: "overlays"
        value:
        - key: branch
          expression: "body.ref.split('/')[2]"
    bindings:
      - ref: simple-pipeline-binding
    template:
      ref: simple-pipeline-template
