apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-3
  namespace: openshift-gitops
  labels:
    kustomizeIdentifer: app-to-update
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'