kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-1
  labels:
    app: app-1
spec:
  replicas: 2
  selector:
    matchLabels:
      deployment: app-1
      app: app-1
  template:
    metadata:
      labels:
        deployment: app-1
        app: app-1
    spec:
      containers:
        - name: app-1
          image: quay.io/marrober/layers:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 1
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 100Mi
---
kind: Service
apiVersion: v1
metadata:
  name: app-1
  labels:
    app: app-1
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: app-1
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: app-1
  name: app-1
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: app-1
    weight: 100
