apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: simple-pipeline-3
spec:
  tasks:
##------------------------------------------------------------------
# ls
##------------------------------------------------------------------
    - name: ls
      taskRef:
        kind: Task
        name:  ls
