apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: simple-pipeline-2-pr-
spec:
  pipelineRef:
    name: simple-pipeline-2
  params:
      # Use this Git URL to pull a simple sample application and dockerfile for the construction of the container image. 
      # Update this reference if you clone the repo and make changes or use a completely difference repo.
    - name: git-url
      value: https://github.com/marrober/simple-apps.git
      # Main branch of the git repo
    - name: git-revision
      value: main
      # Directory within the git repo that holds the dockerfile. The example dockerfile makes reference to 
      # files within this directory too.
    - name: app-dir
      value: node/layers
      # The imagestream url for where the created container image will be stored. Update the namespace element if this is
      # created in a different namespace. also update the namespace file in the location namespace/namespace.yaml.
    - name: imagestream-url
      value: image-registry.openshift-image-registry.svc:5000/simple-pipeline-2/my-app
    - name: repo_type
      value: github.com
    - name: myapp-cd-git-url
      value: marrober/simple-apps
    - name: my-app-cd-git-repo-name
      value: simple-apps
    - name: my-app-cd-git-repo-path-to-content-development
      value: pipelines/simplePipeline-2/deployment
    - name: my-app-cd-git-user-name
      value: "Mark Roberts"
    - name: my-app-cd-git-user-email
      value: "mroberts@redhat.com"
    - name: my-app-cd-git-commit-comment-dev
      value: "Update from ci process"
    - name: openshift_app_name
      value: simple-app-2
    - name: runtime_image_name
      value: my-app
  workspaces:
  - name: files
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
  - name: resources
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
        
          requests:
            storage: 5Gi