kind: Secret
apiVersion: v1
metadata:
  name: sonardb
  namespace: sonarqube
  uid: 16b170d4-3070-4620-a70a-9c93404e7435
  resourceVersion: '88532'
  creationTimestamp: '2023-10-17T08:30:35Z'
  labels:
    app: sonarqube
    app.kubernetes.io/instance: sonarqube-local-cluster
    template: postgresql-persistent-template
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","data":{"database-name":"c29uYXI=","database-password":"UGhFS05HMFJlamJxSnQyOA==","database-user":"dXNlcmRseHd1ZDQ3"},"kind":"Secret","metadata":{"annotations":{},"labels":{"app":"sonarqube","app.kubernetes.io/instance":"sonarqube-local-cluster","template":"postgresql-persistent-template"},"name":"sonardb","namespace":"sonarqube"},"type":"Opaque"}
  managedFields:
    - manager: argocd-application-controller
      operation: Update
      apiVersion: v1
      time: '2023-10-17T08:30:35Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:database-name': {}
          'f:database-password': {}
          'f:database-user': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/instance': {}
            'f:template': {}
        'f:type': {}
data:
  database-name: sonar
  database-password: sonar-random-password
  database-user: sonardb-user
type: Opaque