# .....
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build
spec:
  params:
    - name: TLSVERIFY
      default: "false"
      description: Verify the TLS on the registry endpoint
      type: string
    - name: STORAGE_DRIVER
      description: The Buildah storage STORAGE_DRIVER
      type: string
    - name: app-dir
      type: string
    - name: source-image-name
      type: string
  stepTemplate:
    env:
      - name: "HOME"
        value: "/tekton/home"
  steps:
    - name: get-source-image-location
      command:
      - /bin/sh
      - -c
      args:
      - |-
        echo "$(params.source-image-name)"

        oc get is/$(params.source-image-name) -o jsonpath='{.status.dockerImageRepository}' > /source/$(params.source-image-name).location

        cat /source/nodejs-16.location

      image: default-route-openshift-image-registry.apps.skylake.demolab.local/tkn-pac-simple-apps/nodejs-16
      resources: {}
      securityContext:
        capabilities:
          add:
          - SETFCAP
      workingDir: /source
    - name: package-node-app
      command:
      - /bin/sh
      - -c
      args:
      - |-
        # npm install -g npm@9.2.0
        npm install
        ls -al
      image: default-route-openshift-image-registry.apps.skylake.demolab.local/tkn-pac-simple-apps/nodejs-16
      resources: {}
      securityContext:
        capabilities:
          add:
          - SETFCAP
      workingDir: /source/$(params.app-dir)
    - name: build
      command:
      - buildah
      - bud
      - --tls-verify=$(params.TLSVERIFY)
      - --storage-driver=$(params.STORAGE_DRIVER)
      - --root
      - /resources/buildah-containers
      - --layers
      - -f
      - ./dockerfile
      - -t
      - my-container-image
      - .
      image: default-route-openshift-image-registry.apps.skylake.demolab.local/tkn-pac-simple-apps/buildah
      resources: {}
      securityContext:
        capabilities:
          add:
          - SETFCAP
      workingDir: /source/$(params.app-dir)
    - name: list-images
      command:
      - buildah
      - images
      - --storage-driver=$(params.STORAGE_DRIVER)
      - --root
      - /resources/buildah-containers
      image: default-route-openshift-image-registry.apps.skylake.demolab.local/tkn-pac-simple-apps/buildah
      resources: {}
      securityContext:
        capabilities:
          add:
          - SETFCAP
      workingDir: /
  volumes:
    - emptyDir: {}
      name: envparams
  workspaces:
    - mountPath: /source
      name: source
    - mountPath: /resources
      name: resources
