apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: app-build-template
spec:
  params:
  - name: gitrepository.url
  - name: gitrevision
  - name: branch
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: simple-pipeline-1-run-tr-
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: simple-pipeline
      params:
        - name: git-url
          value: $(tt.params.gitrepository.url)
        - name: git-revision
          value: $(tt.params.gitrevision)
        - name: branch
          value: $(tt.params.branch)
          # Directory within the git repo that holds the dockerfile. The example dockerfile makes reference to 
          # files within this directory too.
        - name: app-dir
          value: node/layers
          # The imagestream url for where the created container image will be stored. Update the namespace element if this is
          # created in a different namespace. also update the namespace file in the location namespace/namespace.yaml.
        - name: imagestream-url
          value: image-registry.openshift-image-registry.svc:5000/simple-pipeline-1/my-app
      workspaces:
      - name: files
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
      - name: resources
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
