apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- pipelines/pipeline.yaml
- tasks/build.yaml
- tasks/pushImageToOCPImageStream.yaml
- smee/deployment.yaml
- triggers/eventListener.yaml
- triggers/eventListenerRoute.yaml
- triggers/triggerBinding.yaml
- triggers/triggerTemplate.yaml
#- role-binding/pipeline-sa.yaml


