apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: simple-pipeline-pr-
spec:
  pipelineRef:
    name: simple-pipeline
  params:
    - name: git_url
      value: https://github.com/marrober/simple-apps.git
    - name: git_revision
      value: main
    - name: app-dir
      value: node/layers
    - name: imagestream-url
      value: image-registry.openshift-image-registry.svc:5000/simple-pipeline/my-app
    - name: quay-io-account
      value: "marrober"
    - name: quay-io-repository
      value: "simple-pipeline"
    - name: quay-io-image-tag-name
      value: "latest"
  workspaces:
  - name: files
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
  - name: resources
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
