apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: simple-pipeline-pr-
spec:
  pipelineRef:
    name: simple-pipeline
  params:
    - name: git_fullname
      value: ""
    - name: revision
      value: ""
    - name: commit_prior_revision
      value: ""
    - name: commit_ref
      value: ""
    - name: commit_id
      value: ""
    - name: commit_date
      value: ""
    - name: commit_message
      value: ""
    - name: commit_author
      value: ""
    - name: git_url
      value: https://github.com/marrober/simple-apps.git
    - name: git_revision
      value: main
    - name: app-dir
      value: node/layers
  workspaces:
  - name: files
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
  - name: resources
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
