apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-1
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements: 
      - cluster: local-cluster
        url: https://kubernetes.default.svc
      - cluster: pentium
        url: https://api.pentium.demolab.local:6443
  template:
    metadata:
      annotations:
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: openshift-gitops
        argocd.argoproj.io/skip-reconcile: "true" 
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true" 
      name: '{{cluster}}-app-1'
    spec:
      destination:
        namespace: app-1
        server: '{{url}}'
      project: default
      source:
        path: Argo-Apps/app-1
        repoURL: https://github.com/marrober/simple-apps.git
        targetRevision: main
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true